server:
  port: 8087
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    url: jdbc:oracle:thin:@10.0.11.83:1545/srm.weichai.com
    username: lisongyue
    password: lisongyue
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.demo.supply.entity
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: false
    db-config:
      id-type: UUID
      field-strategy: NOT_EMPTY
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0

